version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: pip install pipenv
      - run: pipenv install
      - run: pipenv run autopep8 routes.py -i
      - run: pipenv run autopep8 models.py -i
      - run: pipenv run autopep8 forms.py -i
  build:
    branches:
      only:
       - master
       - develop
    machine: true
    steps:
      - checkout
      - run: docker build . -t gcr.io/${GCP_PROJECT}/mblog:$CIRCLE_SHA1
      - run: echo ${GOOGLE_AUTH} > ${HOME}/GCP-KEY.json
      - run: gcloud auth activate-service-account --key-file ${HOME}/GCP-KEY.json
      - run: gcloud --quiet config set project ${GCP_PROJECT}
      - run: gcloud docker -- push gcr.io/${GCP_PROJECT}/mblog:$CIRCLE_SHA1
