version: 2.1
jobs:
  build:
    environment:
      SHORT_GIT_HASH: $(echo $CIRCLE_SHA1 | cut -c -7)
    machine: true
    steps:
      - checkout
      - run: docker build . -t gcr.io/${GCP_PROJECT}/mblog:$CIRCLE_BRANCH-$SHORT_GIT_HASH
  deploy:
    machine: true
    steps:
      - run: echo ${GOOGLE_AUTH} > ${HOME}/GCP-KEY.json
      - run: gcloud auth activate-service-account --key-file ${HOME}/GCP-KEY.json
      - run: gcloud --quiet config set project ${GCP_PROJECT}
      - run: gcloud docker -- push gcr.io/${GCP_PROJECT}/mblog:$CIRCLE_BRANCH-$SHORT_GIT_HASH
