version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker:
         docker_layer_caching: true 
      - run: docker build . -t mblog
